"""pictures table

Revision ID: 734396663d26
Revises: 
Create Date: 2021-11-05 20:17:06.332797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734396663d26'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('picture',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('painter', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_picture_painter'), 'picture', ['painter'], unique=False)
    op.create_index(op.f('ix_picture_title'), 'picture', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_title'), table_name='picture')
    op.drop_index(op.f('ix_picture_painter'), table_name='picture')
    op.drop_table('picture')
    # ### end Alembic commands ###
