"""add column image

Revision ID: e13fd119a619
Revises: 734396663d26
Create Date: 2021-11-05 23:58:12.942779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13fd119a619'
down_revision = '734396663d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture', sa.Column('image', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_picture_image'), 'picture', ['image'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_picture_image'), table_name='picture')
    op.drop_column('picture', 'image')
    # ### end Alembic commands ###
